RPCSite/Models/FavoriteClient.cs
using System.Collections.Generic;
using RPCSite.Stats;

namespace RPCSite.Models
{
    public class FavoriteClient
    {
        public int ClientId { get; set; }
        public string Username { get; set; }
        public string ClientNetworkName { get; set; }

        public string CurrentState { get; set; }

        public string WorkTimePercentage { get; set; }

        public static FavoriteClient CreateFromEntity(RemotePowerControllerTestCore.Entities.Client client, RemotePowerControllerTestCore.Entities.User user, 
            RemotePowerControllerTestCore.Entities.ClientState state, List<RemotePowerControllerTestCore.Entities.ClientStateAudit> clientStateAudits)
        {
            var favoriteClientDetailsModel = new List<Models.ClientDetails>();
            foreach (var clientStateAudit in clientStateAudits)
            {
                favoriteClientDetailsModel.Add(ClientDetails.ConvertFromEntity(clientStateAudit));
            }
            var workTimePercentage = 100 - (new StatHandler(favoriteClientDetailsModel)).GetWorkPercentage();
            return new FavoriteClient
            {
                ClientId = client.ClientId,
                Username = user.Username,
                ClientNetworkName = client.NetworkName,
                CurrentState = Models.Client.GetStringCurrentState(state.CurrentState),
                WorkTimePercentage = (workTimePercentage <= 1) ? "0.00" : workTimePercentage.ToString("#.##"),
            };
        }
    }

    public class NotUserClient
    {
        public int ClientId { get; set; }
        public string Username { get; set; }
        public string ClientNetworkName { get; set; }
        public bool IsFavorite { get; set; }
        public string WorkTimePercentage { get; set; }

        public static NotUserClient ConvertFromEntity(RemotePowerControllerTestCore.Entities.Client client, RemotePowerControllerTestCore.Entities.User user, bool isFavorite,
            List<RemotePowerControllerTestCore.Entities.ClientStateAudit> clientStateAudits)
        {
            var notUserClientDetailsModel = new List<Models.ClientDetails>();
            foreach (var clientStateAudit in clientStateAudits)
            {
                notUserClientDetailsModel.Add(ClientDetails.ConvertFromEntity(clientStateAudit));
            }
            var workTimePercentage = 100 - (new StatHandler(notUserClientDetailsModel)).GetWorkPercentage();
            return new NotUserClient
            {
                ClientId = client.ClientId,
                Username = user.Username,
                ClientNetworkName = client.NetworkName,
                IsFavorite = isFavorite,
                WorkTimePercentage = (workTimePercentage <= 1) ? "0.00" : workTimePercentage.ToString("#.##"),
            };
        }
    }
}

RPCSite/Controllers/FavoriteClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using RemotePowerControllerTestCore;
using RemotePowerControllerTestCore.Entities;
using RemotePowerControllerTestCore.Repositories.Interfaces;
using RPCSite.Models;
using WebMatrix.WebData;
using Client = RemotePowerControllerTestCore.Entities.Client;
using User = RemotePowerControllerTestCore.Entities.User;

namespace RPCSite.Controllers
{
    public class FavoriteClientController : Controller
    {
        private IGenericRepository<User> _userRepository;
        private IGenericRepository<Client> _clientRepository;
        private IGenericRepository<ClientState> _clientStateRepository;
        private IGenericRepository<ClientStateAudit> _clientStateAuditRepository;
        private IGenericRepository<Favorite> _favoriteRepository;

        public FavoriteClientController(IGenericRepository<User> userRepository, IGenericRepository<Client> clientRepository, 
            IGenericRepository<ClientState> clientStateRepository, IGenericRepository<Favorite> favoriteRepository, IGenericRepository<ClientStateAudit> clientStateAuditRepository)
        {
            _userRepository = userRepository;
            _clientRepository = clientRepository;
            _clientStateRepository = clientStateRepository;
            _favoriteRepository = favoriteRepository;
            _clientStateAuditRepository = clientStateAuditRepository;
        }

        //
        // GET: /FavoriteClient/
        [Authorize]
        public ActionResult Index(string query)
        {
            var favoriteClientIds = _favoriteRepository.Get(f => f.UserId == WebSecurity.CurrentUserId).ToList();
            var favoriteClients = new List<Client>();
            foreach (var favoriteClientId in favoriteClientIds)
            {
                var favoriteClient = _clientRepository.GetByID(favoriteClientId.ClientId);
                favoriteClients.Add(favoriteClient);
            }
            var result = new List<Models.FavoriteClient>();
            if (String.IsNullOrWhiteSpace(query))
                foreach (var favoriteClient in favoriteClients)
                {
                    var favoriteClientOwner = _userRepository.GetByID(favoriteClient.UserId);
                    var favoriteClientState = _clientStateRepository.GetByID(favoriteClient.ClientId);
                    var favoriteClientStateAudit =  _clientStateAuditRepository.Get(csa => csa.ClientId == favoriteClient.ClientId).ToList();
                    result.Add(FavoriteClient.CreateFromEntity(favoriteClient, favoriteClientOwner, favoriteClientState, favoriteClientStateAudit));
                }
            else
            {
                foreach (var favoriteClient in favoriteClients)
                {
                    var favoriteClientOwner = _userRepository.GetByID(favoriteClient.UserId);
                    var isSearchedClientName = favoriteClient.NetworkName.IndexOf(query, 0, StringComparison.InvariantCultureIgnoreCase) >= 0;
                    var isSearchedClientOwner = favoriteClientOwner.Username.IndexOf(query, 0, StringComparison.InvariantCultureIgnoreCase) >= 0;
                    if (!isSearchedClientName && !isSearchedClientOwner) continue;
                    var favoriteClientState = _clientStateRepository.GetByID(favoriteClient.ClientId);
                    var favoriteClientStateAudit = _clientStateAuditRepository.Get(csa => csa.ClientId == favoriteClient.ClientId).ToList();
                    result.Add(FavoriteClient.CreateFromEntity(favoriteClient, favoriteClientOwner, favoriteClientState, favoriteClientStateAudit));
                }
            }

            return View(result);
        }

        //
        // GET: /FavoriteClient/Details/5

        /*public ActionResult Details(int id)
        {
            return View();
        }*/

        //
        // GET: /FavoriteClient/Create
        [Authorize]
        public ActionResult Add(string query)
        {
            var notCurrentUserClients = _clientRepository.Get(c => c.UserId != WebSecurity.CurrentUserId).ToList();
            var currentUserFavoriteClientIds = _favoriteRepository.Get(f => f.UserId == WebSecurity.CurrentUserId).ToList();
            var result = new List<Models.NotUserClient>();
            if (String.IsNullOrWhiteSpace(query))
                foreach (var notCurrentUserClient in notCurrentUserClients)
                {
                    var notUserClientOwner = _userRepository.GetByID(notCurrentUserClient.UserId);
                    var notUserClientStateAudit = _clientStateAuditRepository.Get(csa=>csa.ClientId == notCurrentUserClient.ClientId).ToList();
                    var isFavorite = false;
                    foreach (var currentUserFavoriteClientId in currentUserFavoriteClientIds)
                        if (notCurrentUserClient.ClientId == currentUserFavoriteClientId.ClientId) isFavorite = true;
                    result.Add(NotUserClient.ConvertFromEntity(notCurrentUserClient, notUserClientOwner, isFavorite, notUserClientStateAudit));
                }
            else
                foreach (var notCurrentUserClient in notCurrentUserClients)
                {
                    var notUserClientOwner = _userRepository.GetByID(notCurrentUserClient.UserId);
                    var isSearchedClientName = notCurrentUserClient.NetworkName.IndexOf(query, 0, StringComparison.InvariantCultureIgnoreCase) >= 0;
                    var isSearchedClientOwner = notUserClientOwner.Username.IndexOf(query, 0, StringComparison.InvariantCultureIgnoreCase) >= 0;
                    if(!isSearchedClientName && !isSearchedClientOwner) continue;
                    var notUserClientStateAudit = _clientStateAuditRepository.Get(csa => csa.ClientId == notCurrentUserClient.ClientId).ToList();
                    var isFavorite = false;
                    foreach (var currentUserFavoriteClientId in currentUserFavoriteClientIds)
                    {
                        if (notCurrentUserClient.ClientId == currentUserFavoriteClientId.ClientId) isFavorite = true;
                    }
                    result.Add(NotUserClient.ConvertFromEntity(notCurrentUserClient, notUserClientOwner, isFavorite, notUserClientStateAudit));
                }
            return View(result);
        }

        //
        // POST: /FavoriteClient/Create

        [HttpPost]
        public ActionResult Add(int id)
        {
            try
            {
                // TODO: Add insert logic here
                var favoritePair = new Favorite
                {
                    UserId = WebSecurity.CurrentUserId,
                    ClientId = id,
                };
                _favoriteRepository.Insert(favoritePair);
                return RedirectToAction("Add");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /FavoriteClient/Edit/5

        /*public ActionResult Edit(int id)
        {
            return View();
        }*/

        //
        // POST: /FavoriteClient/Edit/5

        /*[HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }*/

        //
        // GET: /FavoriteClient/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                var favoritePair = new Favorite
                {
                    UserId = WebSecurity.CurrentUserId,
                    ClientId = id,
                };
                _favoriteRepository.Delete(favoritePair);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        //
        // POST: /FavoriteClient/Delete/5

        //[HttpPost]
        /*public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var favoritePair = new Favorite
                {
                    UserId = WebSecurity.CurrentUserId,
                    ClientId = id,
                };
                _favoriteRepository.Delete(favoritePair);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }*/
    }
}

RPCSite/Views/FavoriteClient/Add.cshtml
@model IList<RPCSite.Models.NotUserClient>

@{
    ViewBag.Title = "Add Favorite Client";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="padding-left: 15px;">
    <div class="btn-group btn-group-lg nav-group">
        @Html.ActionLink("Clients", "Index", "Client", null, new {@class = "btn btn-default"})
        @Html.ActionLink("Favorites", "Index", "FavoriteClient", null, new {@class = "btn btn-default"})
        @Html.ActionLink("All", "Add", "FavoriteClient", null, new {@class = "btn btn-default active"})
        <a href="@Url.Action("Index", "NetworkGroup")" class="btn btn-default">Network<sup>beta</sup></a>
    </div>
</div>

@if (!Model.Any())
{
    <h3>You have already added all favorites</h3>
}

@for (int i = 0, colCount = 3; i < Model.Count; i += colCount)
{
    <div class="row nuclient-row">
        @for (int j = 0; j < colCount && ((i + j) < Model.Count); j++)
        {
            <div id="not-user-client-block-@Model[i+j].ClientId" class="col-sm-6 col-md-6 col-lg-4 nuclient-unwrap nuclient-wrap-@i nuclient-panel">
                <div class="panel panel-default panel-border-bottom-0">
                    <div class="panel-heading clearfix bg-black border-top-0">
                         <h3 class="panel-title pull-left white" style="padding-top: 4px;">
                             <a href="#" id="notuserclient-itemstate-@Model[i+j].ClientId"><span class="glyphicon glyphicon-off"></span></a>
                             <a class="not-underlined collapse-trigger" data-toggle="collapse" data-target="#notuserclient-collapse-@Model[i+j].ClientId" >
                                 <span class="networkname">@Model[i+j].ClientNetworkName </span><span class="greenyellow" title="Time PC was turned on">(@Model[i+j].WorkTimePercentage%)</span>
                             </a>
                         </h3>
                         <span class="pull-right">
                             <a class="btn btn-sm white hover-blue" title="See details" href="@Url.Action("Details", "Client", new {id=Model[i+j].ClientId})"><span class="glyphicon glyphicon-th-list"></span></a>
                             <a id="btnAddRemoveFav-@Model[i+j].ClientId" class="btn btn-sm isFav-@Model[i+j].IsFavorite.ToString()" href="#"><span class="glyphicon glyphicon-star"></span></a>
                         </span>
                    </div><!--<div class="panel-heading clearfix bg-black border-top-0">-->
                    <div id="notuserclient-collapse-@Model[i + j].ClientId" class="panel-collapse collapse in">
                         <div class="panel-footer text-center">
                             PC Owner: @Model[i+j].Username
                         </div><!--<div class="panel-footer">-->
                     </div>
                </div><!--<div class="panel panel-default panel-border-bottom-0">-->
            </div><!--<div id="not-user-client-block-@Model[i+j].ClientId" class="col-sm-6 col-md-6 col-lg-4 unwrap">-->
        }
    </div>
}

@section scripts{
    <script type="text/javascript">
        var checkStates = function () {
            $.ajax({
                url: "@Url.Action("CheckStates","Client")",
                type: "POST",
                success: function (data) {
                    $.each(data, function (i, obj) {
                        switchStateColor(obj.ClientId, obj.CurrentState);
                    });
                }
            });
        };

        var switchStateColor = function (id, currentState) {
            var itemstateId = "#notuserclient-itemstate-" + id;
            $(itemstateId).attr("title", currentState);
            switch (currentState) {
                case "On":
                    $(itemstateId).css("color", "#4cae4c");
                    break;
                case "Off":
                    $(itemstateId).css("color", "#d43f3a");
                    break;
                case "Process...":
                    $(itemstateId).css("color", "#eea236");
                    break;
                case "Sleep":
                    $(itemstateId).css("color", "#eea236");
                    break;
                case "On (Client is not running)":
                    $(itemstateId).css("color", "#eea236");
                    break;
                case "Server Inaccessible":
                    $(itemstateId).css("color", "#eea236");
                    break;
            }
        };
        
        var restoreNotUserClientCollapsedPartStates = function () {
            $("div.panel-collapse.collapse").each(function () {
                var arrInfo = $(this).attr("id").split("-");
                var notUserClientId = arrInfo[2];
                var notUserClientCollapsedPartId = "#notuserclient-collapse-" + notUserClientId;
                //console.log(notUserClientCollapsedPartId);
                if (localStorage.getItem(notUserClientCollapsedPartId) == "true") {
                    //console.log(localStorage.getItem(favCollapsedPartId));
                    $(notUserClientCollapsedPartId).removeClass("in");
                }
                //else $(clientCollapsedPartId).removeClass("in").addClass("in");
            });
        };

        checkStates();
        $(document).ready(function() {
            setInterval(checkStates, 1500);
            
            $("a.isFav-True").removeClass("yellow hover-white remove-fav").addClass("yellow hover-white remove-fav").attr("title", "Remove favorite");
            $("a.isFav-False").removeClass("white hover-yellow add-fav").addClass("white hover-yellow add-fav").attr("title", "Add to favorites");
            
            restoreNotUserClientCollapsedPartStates();
            
            $("a.add-fav").on("click", function() {
                var arrInfo = $(this).attr("id").split("-");
                var itemId = arrInfo[1];
                console.log(itemId);
                $.ajax({
                    async: false,
                    url: "@Url.Action("Add","FavoriteClient")",
                    type: "post",
                    data: { "id": itemId },
                    datatype: "json"
                });
                location.reload();
            });

            $("a.remove-fav").on("click", function() {
                var arrInfo = $(this).attr("id").split("-");
                var itemId = arrInfo[1];
                console.log(itemId);
                $.ajax({
                    async: false,
                    url: "@Url.Action("Delete", "FavoriteClient")",
                    type: "post",
                    data: { "id": itemId },
                    datatype: "json"
                });
                location.reload();
            });
            
            $(window).on("resize", function () {
                setSiteTo320();
                setSiteTo1080();
                setSiteTo1200();
            });
            
            $("a.collapse-trigger").on("click", function () {
                var arrInfo = $(this).attr("data-target").split("-");
                var notUserClientId = arrInfo[2];
                var notUserClientCollapsedPartId = "#notuserclient-collapse-" + notUserClientId;
                var isCollapsed = $(notUserClientCollapsedPartId).hasClass("in") ? true : false;
                localStorage.setItem(notUserClientCollapsedPartId, isCollapsed);
                //console.log(localStorage.getItem(favCollapsedPartId));
            });
        });
        
        var setSiteTo1080 = function () {
            if ($(window).width() < 1190 && $(".nuclient-row").length > 0) {
                $(".nuclient-unwrap").unwrap();
                //$(".unwrap").css("padding-left", "0px");
                wrapTwoPanelByRow();
            }
        };

        var wrapTwoPanelByRow = function () {
            var $clientPanel = $("div.nuclient-panel");
            var clientPanelCount = $clientPanel.length;
            var classNameToAdd = "nuclient-wrap-2-";
            console.log(clientPanelCount);
            var clientPanelInRowCount = 2;
            for (var i = 0; i < clientPanelCount; i += clientPanelInRowCount) {
                for (var j = 0; j < clientPanelInRowCount && (i + j) < clientPanelCount; j++) {
                    $("div.nuclient-panel:eq(" + (i + j) + ")").removeClass(classNameToAdd + i);
                    $("div.nuclient-panel:eq(" + (i + j) + ")").addClass(classNameToAdd + i);
                    $("div.nuclient-panel:eq(" + (i + j) + ")").removeClass("nuclient-unwrap-2");
                    $("div.nuclient-panel:eq(" + (i + j) + ")").addClass("nuclient-unwrap-2");
                    console.log(classNameToAdd + i);
                }
            }
            if ($(".nuclient-row-2").length <= 0)
                for (var i = 0; i < clientPanelCount; i += clientPanelInRowCount)
                    $("div." + classNameToAdd + i).wrapAll("<div class='row nuclient-row-2'></div>");
        };

        var setSiteTo1200 = function () {
            if ($(window).width() >= 1190 && $(".nuclient-row-2").length > 0) {
                $(".nuclient-unwrap-2").unwrap();
            }
            if ($(window).width() >= 1190 && $(".nuclient-row").length <= 0) {
                var colCount = 3;
                var count = parseInt('@(Model.Count)');
                for (var i = 0; i < count; i += colCount) {
                    $(".nuclient-wrap-" + i).wrapAll("<div class='row nuclient-row'></div>");
                }
            }
        };
        var setSiteTo320 = function () {
            if ($(window).width() <= 320) {
                $("span.networkname").each(function () {
                    var fullNetworkName = $(this).text();
                    console.log(fullNetworkName);
                    if (fullNetworkName.length > 6) {
                        var shortNetworkName = fullNetworkName.substring(0, 6) + "... ";
                        $(this).text(shortNetworkName);
                    }
                });
            }
        };

        setSiteTo320();
        setSiteTo1080();
        setSiteTo1200();
    </script>
}

RPCSite/Views/FavoriteClient/Index.cshtml
@model IList<RPCSite.Models.FavoriteClient>

@{
    ViewBag.Title = "Favorite Clients";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row" style="padding-left: 15px;">
    <div class="btn-group btn-group-lg nav-group">
        @Html.ActionLink("Clients", "Index", "Client", null, new {@class = "btn btn-default"})
        @Html.ActionLink("Favorites", "Index", "FavoriteClient", null, new {@class = "btn btn-default active"})
        @Html.ActionLink("All", "Add", "FavoriteClient", null, new {@class = "btn btn-default"})
        <a href="@Url.Action("Index", "NetworkGroup")" class="btn btn-default">Network<sup>beta</sup></a>
    </div>    
</div>

@if (!Model.Any())
{
    <h2>You have not favorites yet</h2>
}

@for (int i = 0, colCount = 3; i < Model.Count; i += colCount)
{
    <div class="row fav-row">
         @for (int j = 0; j < colCount && ((i + j) < Model.Count); j++)
         {
             <div id="favorite-block-@Model[i+j].ClientId" class="col-sm-6 col-md-6 col-lg-4 fav-unwrap fav-wrap-@i fav-panel">
                 <div class="panel panel-default panel-border-bottom-0">
                     <div class="panel-heading clearfix bg-black border-top-0">
                         <h3 class="panel-title pull-left white" style="padding-top: 4px;">
                             <a href="#" id="fav-itemstate-@Model[i+j].ClientId"><span class="glyphicon glyphicon-off"></span></a>
                             <a class="not-underlined collapse-trigger" data-toggle="collapse" data-target="#fav-collapse-@Model[i+j].ClientId" >
                                 <span class="networkname">@Model[i+j].ClientNetworkName </span><span class="greenyellow" title="Time PC was turned off">(@Model[i+j].WorkTimePercentage%)</span>
                             </a>
                         </h3>
                         <span class="pull-right">
                             <a class="btn btn-sm white hover-blue" title="See details" href="@Url.Action("Details", "Client", new {id=Model[i+j].ClientId})"><span class="glyphicon glyphicon-th-list"></span></a>
                             <a id="btnDeleteClient-@Model[i+j].ClientId" class="btn btn-sm yellow hover-white delete-fav" title="Remove favorite" href="#"><span class="glyphicon glyphicon-star"></span></a>
                         </span>
                     </div><!--<div class="panel-heading clearfix bg-black border-top-0">-->
                     <div id="fav-collapse-@Model[i + j].ClientId" class="panel-collapse collapse in">
                         <div class="panel-footer text-center">
                             PC Owner: @Model[i+j].Username
                         </div><!--<div class="panel-footer">-->
                     </div>
                 </div><!--<div class="panel panel-default panel-border-bottom-0">-->
             </div><!--<div id="favorite-block-Model[i+j].ClientId" class="col-sm-6 col-md-6 col-lg-4 unwrap">-->
         }
    </div><!--<div class="row">-->
}

@section scripts{
    <script type="text/javascript">
        var checkStates = function () {
            $.ajax({
                url: "@Url.Action("CheckStates","Client")",
                type: "POST",
                success: function (data) {
                    $.each(data, function (i, obj) {
                        switchStateColor(obj.ClientId, obj.CurrentState);
                    });
                }
            });
        };
        
        var switchStateColor = function (id, currentState) {
            var itemstateId = "#fav-itemstate-" + id;
            $(itemstateId).attr("title", currentState);
            switch (currentState) {
                case "On":
                    $(itemstateId).css("color", "#4cae4c");
                    break;
                case "Off":
                    $(itemstateId).css("color", "#d43f3a");
                    break;
                case "Process...":
                    $(itemstateId).css("color", "#eea236");
                    break;
                case "Sleep":
                    $(itemstateId).css("color", "#eea236");
                    break;
                case "On (Client is not running)":
                    $(itemstateId).css("color", "#eea236");
                    break;
                case "Server Inaccessible":
                    $(itemstateId).css("color", "#eea236");
                    break;
            }
        };
        
        var restoreFavCollapsedPartStates = function () {
            $("div.panel-collapse.collapse").each(function () {
                var arrInfo = $(this).attr("id").split("-");
                var favId = arrInfo[2];
                var favCollapsedPartId = "#fav-collapse-" + favId;
                console.log(favCollapsedPartId);
                if (localStorage.getItem(favCollapsedPartId) == "true") {
                    //console.log(localStorage.getItem(favCollapsedPartId));
                    $(favCollapsedPartId).removeClass("in");
                }
                //else $(clientCollapsedPartId).removeClass("in").addClass("in");
            });
        };

        checkStates();
        $(document).ready(function() {
            checkStates();
            setInterval(checkStates, 1500);
            restoreFavCollapsedPartStates();
            $("a.delete-fav").on("click", function() {
                var arrInfo = $(this).attr("id").split("-");
                var itemId = arrInfo[1];
                console.log(itemId);
                $.ajax({
                    async: false,
                    url: "@Url.Action("Delete", "FavoriteClient")",
                    type: "post",
                    data: { "id": itemId },
                    datatype: "json"
                });
                location.reload();
            });
            
            $(window).on("resize", function () {
                setSiteTo320();
                setSiteTo1080();
                setSiteTo1200();
            });
            
            $("a.collapse-trigger").on("click", function () {
                var arrInfo = $(this).attr("data-target").split("-");
                var favId = arrInfo[2];
                var favCollapsedPartId = "#fav-collapse-" + favId;
                var isCollapsed = $(favCollapsedPartId).hasClass("in") ? true : false;
                localStorage.setItem(favCollapsedPartId, isCollapsed);
                //console.log(localStorage.getItem(favCollapsedPartId));
            });
        });
        
        var setSiteTo1080 = function () {
            if ($(window).width() < 1190 && $(".fav-row").length > 0) {
                $(".fav-unwrap").unwrap();
                //$(".unwrap").css("padding-left", "0px");
                wrapTwoPanelByRow();
            }
        };
        
        var wrapTwoPanelByRow = function () {
            var $clientPanel = $("div.fav-panel");
            var clientPanelCount = $clientPanel.length;
            var classNameToAdd = "fav-wrap-2-";
            console.log(clientPanelCount);
            var clientPanelInRowCount = 2;
            for (var i = 0; i < clientPanelCount; i += clientPanelInRowCount) {
                for (var j = 0; j < clientPanelInRowCount && (i + j) < clientPanelCount; j++) {
                    $("div.fav-panel:eq(" + (i + j) + ")").removeClass(classNameToAdd + i);
                    $("div.fav-panel:eq(" + (i + j) + ")").addClass(classNameToAdd + i);
                    $("div.fav-panel:eq(" + (i + j) + ")").removeClass("fav-unwrap-2");
                    $("div.fav-panel:eq(" + (i + j) + ")").addClass("fav-unwrap-2");
                    console.log(classNameToAdd + i);
                }
            }
            if ($(".fav-row-2").length <= 0)
                for (var i = 0; i < clientPanelCount; i += clientPanelInRowCount)
                    $("div." + classNameToAdd + i).wrapAll("<div class='row fav-row-2'></div>");
        };

        var setSiteTo1200 = function () {
            if ($(window).width() >= 1190 && $(".fav-row-2").length > 0) {
                $(".fav-unwrap-2").unwrap();
            }
            if ($(window).width() >= 1190 && $(".fav-row").length <= 0) {
                var colCount = 3;
                var count = 2 //magic number parseInt('(Model.Count)');
                for (var i = 0; i < count; i += colCount) {
                    $(".fav-wrap-" + i).wrapAll("<div class='row fav-row'></div>");
                }
            }
        };
        var setSiteTo320 = function () {
            if ($(window).width() <= 320) {
                $("span.networkname").each(function () {
                    var fullNetworkName = $(this).text();
                    console.log(fullNetworkName);
                    if (fullNetworkName.length > 6) {
                        var shortNetworkName = fullNetworkName.substring(0, 6) + "... ";
                        $(this).text(shortNetworkName);
                    }
                });
            }
        };

        setSiteTo320();
        setSiteTo1080();
        setSiteTo1200();
    </script>
}