RPCSite/Models/Client.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using Common.Ciphers;
using Common.CustomUrlCoder;
using Common.DTO.Enums;
using RPCSite.Stats;

namespace RPCSite.Models
{
    public class Client
    {
        public int ClientId { get; set; }

        [DisplayName("Networkname")]
        public string NetworkName { get; set; }

        [DisplayName("Current state")]
        public string CurrentState { get; set; }

        public string Command { get; set; }

        public string TurnOnLink { get; set; }

        public string TurnOnWithRDLink { get; set; }

        public string WorkTimePercentage { get; set; }

        public static string GetStringCurrentState(State state)
        {
            switch (state)
            {
                case State.InProcess:
                    return "Process...";
                case State.Off:
                    return "Off";
                case State.On:
                    return "On";
                case State.Sleep:
                    return "Sleep";
                case State.OnWithoutClient:
                    return "On (Client is not running)";
                case State.ServerInaccessible:
                    return "Server Inaccessible";
                default:
                    return "Process...";
            }
        }

        public static State GetStateFromString(string state)
        {
            state = state.Trim();
            switch (state)
            {
                case "Process...":
                    return State.InProcess;
                case "Off":
                    return State.Off;
                case "On":
                    return State.On;
                case "Sleep":
                    return State.Sleep;
                case "On (Client is not running)":
                    return State.OnWithoutClient;
                case "Server Inaccessible":
                    return State.ServerInaccessible;
                default:
                    return State.InProcess;
            }
        }

        private static string GetStringCommand(Command command)
        {
            switch (command)
            {
                case Common.DTO.Enums.Command.TurnOn:
                    return "Turn On";
                case Common.DTO.Enums.Command.TurnOff:
                    return "Shut Down";
                case Common.DTO.Enums.Command.GoToSleep:
                    return "Sleep";
                case Common.DTO.Enums.Command.DoNothing:
                    return "0";
                case Common.DTO.Enums.Command.InProcess:
                    return "Process...";
                default:
                    return "Process...";
            }
        }

        public static string[] GetStateEnumStringNames()
        {
            var states = Enum.GetNames(typeof (State));
            var result = new string[states.Length];
            for (var i = 0; i < states.Length; i++)
            {
                result[i] = GetStringCurrentState((State) i);
            }
            return result;
        }

        public static Client CreateFromEntity(RemotePowerControllerTestCore.Entities.User user, RemotePowerControllerTestCore.Entities.Client entityClient ,
            List<RemotePowerControllerTestCore.Entities.ClientStateAudit> clientDetailsEntities)
        {
            return new Client
            {
                ClientId = entityClient.ClientId,
                NetworkName = entityClient.NetworkName,
                CurrentState = GetStringCurrentState(entityClient.ClientState.CurrentState),
                Command = GetStringCommand(entityClient.ClientState.Command),
                WorkTimePercentage = ClientDetails.GetWorkTimePercentage(clientDetailsEntities),
                TurnOnLink = GetTurnOnLink(entityClient.ClientId, user.Username, user.Password),
                TurnOnWithRDLink = GetTurnOnWithRDLink(entityClient.ClientId, user.Username, user.Password)
            };
        }

        public static Client CreateFromClientStateEntity(RemotePowerControllerTestCore.Entities.ClientState entityClientState)
        {
            return new Client
            {
                ClientId = entityClientState.ClientId,
                CurrentState = GetStringCurrentState(entityClientState.CurrentState),
                Command = GetStringCommand(entityClientState.Command)
            };
        }

        public static string GetTurnOnLink(int clientId, string username, string userPassword)
        {
            var encryptedUsername = StringCipher.Encrypt(username, Common.Keys.Passwords.UserNameCipherKey);
            var encodedUsername = CustomUrlCoder.Encode(encryptedUsername);
            var encryptedUserPassword = StringCipher.Encrypt(userPassword, Common.Keys.Passwords.PasswordCipherKey);
            var encodedUserPassword = CustomUrlCoder.Encode(encryptedUserPassword);
            return String.Format("http://{0}/APIClient.svc/TurnON={1}/{2}/{3}", ConfigurationManager.AppSettings["RPCLocalUrl"], clientId, encodedUsername, encodedUserPassword);
        }

        public static string GetTurnOnWithRDLink(int clientId, string username, string userPassword)
        {
            var encryptedUsername = StringCipher.Encrypt(username, Common.Keys.Passwords.UserNameCipherKey);
            var encodedUsername = CustomUrlCoder.Encode(encryptedUsername);
            var encryptedUserPassword = StringCipher.Encrypt(userPassword, Common.Keys.Passwords.PasswordCipherKey);
            var encodedUserPassword = CustomUrlCoder.Encode(encryptedUserPassword);
            return String.Format("http://{0}/APIClient.svc/CreateRDPConnection={1}/{2}/{3}", ConfigurationManager.AppSettings["RPCLocalUrl"], clientId, encodedUsername, encodedUserPassword);
        }
    }
}

RPCSite/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web.Mvc;
using System.Web.Security;
using Common.DTO.Enums;
using Common.Logger;
using Common.Logger.Impl;
using Microsoft.Ajax.Utilities;
using RemotePowerControllerTestCore;
using RemotePowerControllerTestCore.Entities;
using RemotePowerControllerTestCore.Helpers;
using RemotePowerControllerTestCore.Repositories.Interfaces;
using RPCSite.Models;
using RPCSite.RDP;
using WebGrease.Css.Extensions;
using WebMatrix.WebData;
using Group = RemotePowerControllerTestCore.Entities.Group;
using Client = RemotePowerControllerTestCore.Entities.Client;
using User = RemotePowerControllerTestCore.Entities.User;

namespace RPCSite.Controllers
{
    public class ClientController : Controller
    {
        private readonly IGenericRepository<Client> _clientRepository;
        private readonly IGenericRepository<ClientState> _clientStateRepository;
        private readonly IGenericRepository<ClientSettings> _clienSettingsRepository;
        private readonly IGenericRepository<ClientStateAudit> _clientStateAuditRepo;
        private readonly IGenericRepository<User> _userRepository;
        private readonly IGenericRepository<Server> _serverRepository;
        private readonly IGenericRepository<CommandAudit> _commandAuditRepository;
        private readonly IGenericRepository<Group> _groupRepository;
        private readonly ILogger _logger;

        public ClientController(
            IGenericRepository<Client> clientRepository, 
            IGenericRepository<ClientState> clientStateRepository, 
            IGenericRepository<ClientSettings> clientSettingsRepository, 
            IGenericRepository<ClientStateAudit> clientStateAuditRepo, 
            IGenericRepository<User> userRepository,
            IGenericRepository<Server> serveRepository, 
            IGenericRepository<CommandAudit> commandAuditRepository,
            IGenericRepository<Group> groupRepository)
        {
            _clientRepository = clientRepository;
            _clientStateRepository = clientStateRepository;
            _clienSettingsRepository = clientSettingsRepository;
            _clientStateAuditRepo = clientStateAuditRepo;
            _userRepository = userRepository;
            _serverRepository = serveRepository;
            _commandAuditRepository = commandAuditRepository;
            _groupRepository = groupRepository;
            _logger = LoggerFactory.Current.GetLogger<ClientController>();
        }

        //
        // GET: /Client/
        [Authorize]
        public ActionResult Index(string query)
        {
            var clientModels = new List<Models.Client>();
            using (var uow = new RPCUnitOfWork())
            {
                IEnumerable<Client> clients;
                clients = Roles.IsUserInRole(AdminDataHelper.GetAdminRoleName) ? uow.ClientRepository.Get(orderBy:o=>o.OrderByDescending(c=>c.NetworkName)) :
                    uow.ClientRepository.Get(c => c.UserId == WebSecurity.CurrentUserId, orderBy: o => o.OrderByDescending(c => c.NetworkName));
                foreach (var client in clients)
                {
                    var clientOwner = uow.UserRepository.GetByID(client.UserId);
                    var clientDetailsEntities = uow.ClientStateAuditRepository.Get(csa => csa.ClientId == client.ClientId).ToList();
                    var clientModel = Models.Client.CreateFromEntity(clientOwner, client, clientDetailsEntities);
                    clientModels.Add(clientModel);
                }
            }
            return View(clientModels);
        }

        [HttpPost]
        public ActionResult CheckServerActivity()
        {
            var servers = _serverRepository.Get().ToList();
            foreach (var server in servers)
            {
                var timeDiff = DateTime.UtcNow - server.LastActivity;
                var totalSeconds = timeDiff.TotalSeconds;
                if (totalSeconds >= 5)
                {
                    var clients = _clientRepository.Get(c => c.ServerId == server.ServerId).ToList();
                    foreach (var client in clients)
                    {
                        var clientState = _clientStateRepository.GetByID(client.ClientId);
                        if (clientState != null && clientState.CurrentState != State.ServerInaccessible)
                        {
                            clientState.CurrentState = State.ServerInaccessible;
                            _clientStateRepository.Update(clientState);
                        }
                    }
                }
            }
            return Json(new {success = true});
        }

        [HttpPost]
        public ActionResult SwitchCommand(int id, string command)
        {
            Command enumCommand;
            switch (command)
            {
                case "turn_on":
                    enumCommand = Command.TurnOn;
                    break;
                case "shut_down":
                    enumCommand = Command.TurnOff;
                    break;
                case "sleep":
                    enumCommand = Command.GoToSleep;
                    break;
                default:
                    enumCommand = Command.DoNothing;
                    break;
            };
            
            var clientStateToSwitchCommand = _clientStateRepository.GetByID(id);
            clientStateToSwitchCommand.Command = enumCommand;
            _clientStateRepository.Update(clientStateToSwitchCommand);
            string userIP = Request.UserHostAddress;
            var commandAudit = new CommandAudit
            {
                DateTime = DateTime.UtcNow,
                ClientId = id,
                Command = enumCommand,
                UserId = WebSecurity.CurrentUserId,
                UserIP = userIP
            };
            _commandAuditRepository.Insert(commandAudit);
            _logger.Info(String.Format("\tUser: {0}\t{1}\t send command: {2}\t to client:{3}", 
                WebSecurity.CurrentUserId, WebSecurity.CurrentUserName, command, id ));
            return Json(new {success = true});
        }

        [HttpPost]
        public ActionResult CheckStates()
        {
            var clientStates = _clientStateRepository.Get().ToList();
            var result = new List<Models.Client>();
            foreach (var clientState in clientStates)
            {

                result.Add(Models.Client.CreateFromClientStateEntity(clientState));
            }
            return Json(data: result);
        }

        //
        // GET: /Client/Details/5
        [Authorize]
        public ActionResult Details(int id, string sortOrder)
        {
            var client = _clientRepository.GetByID(id);
            var user = _userRepository.GetByID(client.UserId);
            var clientStateAuditEntities = _clientStateAuditRepo.Get(csa => csa.ClientId == id, orderBy:q=>q.OrderByDescending(csa=>csa.DateTime)).ToList();
            var result = new List<ClientDetails>();
            foreach (var clientStateAuditEntity in clientStateAuditEntities)
            {
                result.Add(ClientDetails.ConvertFromEntity(user.Username, client, clientStateAuditEntity));
            }

            var stats = new Stats.StatHandler(result);
            result[0].LongestWorkTime = stats.GetLongestWorkTime();
            result[0].TotalTrackingTime = stats.GetTotalTrackingTime();
            result[0].TotalWorkTime = stats.GetTotalWorkTime();
            
            /*ViewBag.DateTime = String.IsNullOrEmpty(sortOrder) ? "DateTime_desc" : "";
            ViewBag.State = sortOrder == "State" ? "State_desc" : "State";
            switch (sortOrder)
            {
                case "DateTime_desc":
                    result = result.OrderBy(csa => csa.DateTime).ToList();
                    break;
                case "State_desc":
                    result = result.OrderByDescending(csa => csa.State).ThenByDescending(csa => csa.DateTime).ToList();
                    break;
                case "State":
                    result = result.OrderBy(csa => csa.State).ThenByDescending(csa => csa.DateTime).ToList();
                    break;
                default:
                    result = result.OrderByDescending(csa => csa.DateTime).ToList();
                    break;
            }*/
            return View(result);
        }

        //
        // GET: /Client/Create

        /*public ActionResult Create()
        {
            return View();
        }*/

        //
        // POST: /Client/Create

        /*[HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }*/

        //
        // GET: /Client/Edit/5

        /*public ActionResult Edit(int id)
        {
            return View();
        }*/

        //
        // POST: /Client/Edit/5

        /*[HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }*/

        //
        // GET: /Client/Delete/5

        /*public ActionResult Delete(int id)
        {
            var clientEntity = _clientRepository.Get(c => c.ClientId == id, includeProperties: "ClientState").FirstOrDefault();
            var clientModel = Models.Client.CreateFromEntity(clientEntity);
            return View(clientModel);
        }*/

        //
        // POST: /Client/Delete/5

        [HttpPost]
        public ActionResult Delete(int clientId)
        {
            try
            {

RPCSite/Views/Client/Details.cshtml
@model IList<RPCSite.Models.ClientDetails>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="btn-group btn-group-lg nav-group">
    @Html.ActionLink("Clients", "Index", "Client", null, new{@class="btn btn-default"})
    @Html.ActionLink("Favorites", "Index", "FavoriteClient", null, new{@class="btn btn-default"})
    @Html.ActionLink("All", "Add", "FavoriteClient", null, new { @class = "btn btn-default" })
</div>

@if (Model.Any())
{
    <h2>Details for @Model[0].Networkname (@Model[0].Username)</h2>
    <h4>Longest work time  - @Model[0].LongestWorkTime</h4>
    <h4>Total tracking time - @Model[0].TotalTrackingTime</h4>
    <h4>Total work time - @Model[0].TotalWorkTime</h4>
}

<div id="chart" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto; width: 100%"></div>
<!--<p>
    @Html.ActionLink("Create New", "Create")
</p>-->
<table id="tblDetails" class="table table-bordered">
    <tr>
        <th>
            DateTime
            <a href="@Url.Action("Details", "Client", new { sortOrder = ViewBag.DateTime })"><img id=""  class="" src="~/Content/images/Sorting.png" alt="Sort" title="Sort"/></a>
        </th>
        <th>
            State
            <a href="@Url.Action("Details", "Client", new { sortOrder = ViewBag.State })"><img id=""  class="" src="~/Content/images/Sorting.png" alt="Sort" title="Sort"/></a>
        </th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
        </tr>
    }

</table>
<!--@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })-->

@section scripts{
    <script type="text/javascript">
        var colorTable = function() {
            $("#tblDetails tr").each(function() {
                var tdValue = $(this).find("td:last-child").text();
                console.log(tdValue);
                if (tdValue.indexOf("Off") >= 0)
                    $(this).addClass("danger");
                if (tdValue.indexOf("On") >= 0)
                    $(this).addClass("success");
            });
        };
        var getSecondsFromHours = function(hours) {
            return (hours * 3600);
        };
        var getSecondsFromMinutes = function(hours) {
            return (hours * 60);
        };

        var getTotalSecondsFromTimeSpan = function (timespan) {
            var totalTimeArr = timespan.split(":");
            var totalSeconds = getSecondsFromHours(parseInt(totalTimeArr[0])) + getSecondsFromMinutes(parseInt(totalTimeArr[1])) + parseFloat(totalTimeArr[2]);
            return totalSeconds;
        };
        $(document).ready(function () {
            Highcharts.setOptions({
                colors: ['#24CBE5', '#50B432']
            });
            var totalSeconds = getTotalSecondsFromTimeSpan("@(Model[0].TotalTrackingTime)");
            var totalWorkingSeconds = getTotalSecondsFromTimeSpan("@(Model[0].TotalWorkTime)");
            var workTimePercentage = (totalWorkingSeconds * 100) / totalSeconds;
            var noWorkTimePercentage = 100 - workTimePercentage;
            console.log(totalSeconds + "-" + totalWorkingSeconds);
            $('#chart').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: 1,//null,
                    plotShadow: false
                },
                title: {
                    text: 'Work time'
                },
                tooltip: {
                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Work Time Pie',
                    data: [
                        ['Free Time', noWorkTimePercentage],
                        {
                            name: 'Work Time',
                            y: workTimePercentage,
                            sliced: true,
                            selected: true
                        }
                    ]
                }]
            });
            colorTable();
        });
    </script>
}

RPCSite/Views/Client/TurningOn.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" href="~/Content/images/favicon.ico"/>
    <title>RPC Turn On</title>
     @Styles.Render("~/Content/bootstrapcss")
    <link href="~/Content/cover.css" rel="stylesheet">
</head>
    <body>
        <div class="site-wrapper">

            <div class="site-wrapper-inner">

                <div class="cover-container">

                    <div class="masthead clearfix">
                        <div class="inner">
                            <h3 class="masthead-brand"></h3>
                            <ul class="nav masthead-nav">
                                <li class="active"><a href="#"></a></li>
                                <li><a href="#"></a></li>
                                <li><a href="#"></a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="inner cover">
                        <h1 class="cover-heading"><img src="~/Content/images/RPCIcon.png"/>Remote Power Controller</h1>
                        <p class="lead">Turn On command to client @(ViewBag.Name ?? Html.Raw("&nbsp;")) was sent.</p>
                        <p class="lead">
                            <!--<a href="#" class="btn btn-lg btn-default">Learn More</a>-->
                        </p>
                    </div>

                    <div class="mastfoot">
                        <div class="inner">
                            
                        </div>
                    </div>

                </div>

            </div>

        </div>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jqueryui")
        @Scripts.Render("~/bundles/bootstrapjs")
    </body>
</html>